routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function(){
	return redirect(app()->getLocale());
});

Route::group(['prefix' => '{locale}', 'where' => ['locale' => '[a-zA-Z]{2}'], 'middleware' => 'setlocale'], function () {

	//Route::get('detail/room/{id}', 'RoomController@showDetails')->name('showDetails');

Auth::routes(['verify' => true]);

Route::get('/test/{id}', 'BookingController@apiExtendBooking');

Route::get('register', 'Auth\RegisterController@showRegistrationForm')->middleware('hasInvitation')->name('register');

//Route::get('/', 'HomeController@getLocale')->name('test');

Route::get('email/verify/{id}/{hash}', 'Auth\VerificationController@verify')->name('verification.route');

	Route::group(['middleware' => 'auth'], function () {

		Route::get('/', 'RoomController@showRooms')->name('landingPage');	
		Route::get('room/{id}/booking', 'BookingController@showForm')->name('bookings.create');
	    Route::post('detail/room/{id}/booking/store', 'BookingController@storeBooking')->name('bookings.store');
	    Route::get('dashboard', 'BookingController@userDashboard')->name('user.dashboard');
	    Route::get('edit/{booking}/{roomId}/{date}', 'BookingController@showEditForm')->name('editForm');
	    Route::put('edit/{booking}/{roomId}/save', 'BookingController@edit')->name('edit');
	    Route::get('profile/{id}', 'UserController@showUserEditForm')->name('showUserEditForm');
		Route::put('profile/edit/{id}', 'UserController@editUsers')->name('editUsers');
		Route::delete('profile/delete/{id}', 'UserController@deactivateUser')->name('deactivateUser');
		Route::get('dashboard/test', 'BookingController@showBookingInLinkedUserDashboard')->name('test');

	});



});

Route::delete('cancel/{booking}', 'BookingController@cancel')->name('cancel');

Route::get('booking_controller/read', 'BookingController@read')->name('booking_controller.read');

Route::group(['prefix' => 'admin' , 'middleware' => ['auth' => 'admin']], function(){

	Route::get('/', 'HomeController@AdminHome')->name('adminHome');
	Route::get('rooms/export/', 'RoomController@export')->name('rooms.export');
	Route::get('trashed-rooms', 'RoomController@trashed')->name('trashed-rooms.index');
	Route::put('restore-room/{room}', 'RoomController@restore')->name('restore-room');
	Route::get('users', 'UserController@listUsers')->name('listUsers');
	Route::get('admins', 'UserController@listAdmins')->name('listAdmins');
	Route::put('user/change-role/{user}', 'UserController@changeRole')->name('changeRole');
	Route::delete('user/delete/{user}', 'UserController@destroy')->name('users.destroy');
	Route::get('trashed-users', 'UserController@trashed')->name('trashed-users.index');
	Route::put('restore-user/{user}', 'UserController@restore')->name('restore-user');
	Route::get('users/export/', 'UserController@export')->name('users.export');
	Route::resource('rooms', 'RoomController');
	Route::get('import', 'RoomController@roomImportForm')->name('import');
	Route::post('import/upload', 'RoomController@roomImport')->name('rooms.import');
	Route::get('invite', 'UserController@inviteForm')->name('inviteForm');
	Route::post('invite/store', 'InvitationController@store')->name('storeInvitation');
});


Route::get('{any}', function () {
    return view('welcome');
})->where('any','.*')->name('all');

app/Room.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Translatable\HasTranslations;

class Room extends Model
{

	use SoftDeletes;
	use HasTranslations;

    protected $fillable = [

    	'name', 'description', 'location', 'image',

    ];

    public $translatable = ['description'];

    public function booking(){
        return $this->hasMany(Booking::class)->with('user');
    }

}

app/Http/Controllers/RoomController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\Rooms\CreateRoomsRequest;
use App\Http\Requests\Rooms\UpdateRoomsRequest;
use App\Room;
use App\Booking;
use Illuminate\Support\Facades\Storage;
use App\Exports\RoomsExport;
use Maatwebsite\Excel\Facades\Excel;
use App\Http\Resources\RoomCollection;
use App\Imports\RoomsImport;
use Carbon;
use Illuminate\Support\Facades\Cookie;
use Auth;
use App\User;

class RoomController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        return view('rooms.index')->with('rooms', Room::all());

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('rooms.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRoomsRequest $request)
    {

        //upload image
        $image = ($request->image->store('rooms'));


        //create room
        Room::create([

            'name' => $request->name,
            'description' => [
                'en' => $request->descriptionEN,
                'nl' => $request->descriptionNL
            ],
            'location' => $request->location,
            'image' => $image


        ]);

        //flash success message
        session()->flash('success', 'Room created successfully!');

        //return redirect back

        return redirect(route('rooms.index'));

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Room $room)
    {

        return view('rooms.create')->with('room', $room);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRoomsRequest $request, $id)
    {

        //check if new image

        //$data = $request->only(['name', 'descriptionEN', 'descriptionNL', 'location']);
        $room = Room::whereId($id)->firstOrFail();

        $hasImage = false;

        if ($request->hasFile('image')) 
        {
            
            //upload it
            $image = $request->image->store('rooms');

            //delete old image
            Storage::delete($room->image);

            $data['image'] = $image;

            $hasImage = true;

        }
        

        //update attributes
        $room::whereId($id)->update([

            'name' => $request->name,
            'description' => [
                'en' => $request->descriptionEN,
                'nl' => $request->descriptionNL
            ],
            'location' => $request->location,

        ]);

        if ($hasImage) 
        {
            
            $room::whereId($id)->update([
                'image' => $image,
            ]);
            
        }

        // flash message
        session()->flash('success', 'Room updated successfully.');

        // redirect user
        return redirect(route('rooms.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //find the room in the DB
        $room = Room::withTrashed()->where('id', $id)->firstOrFail();

        //if user is softdeleted, then force delete, else soft delete
        if ($room->trashed()) 
        {

            Storage::delete($room->image);

            $room->forceDelete();

            //show success message
            session()->flash('success', 'Room deleted successfully!');

            //redirect back
            return redirect(route('trashed-rooms.index'));

        }
        else 
        {

            $room->delete();

            $bookings = Booking::where('room_id', $id)->get();

            foreach ($bookings as $b) {
                $b->delete();
            }

            //show success message
            session()->flash('success', 'Room trashed successfully!');

            //redirect back
            return redirect(route('rooms.index'));

        }

    }

    /**
     * Show trashed rooms
     *
     * @return \Illuminate\Http\Response
     */
    public function trashed(Room $room)
    {

        $trashed = Room::onlyTrashed()->get();


        return view('rooms.index')->with('rooms', $trashed);

    }

    public function restore($id)
    {

        //find the room in the DB
        $room = Room::withTrashed()->where('id', $id)->firstOrFail();

        $room->restore();

        $bookings = Booking::withTrashed()->where('room_id', $id)->get();

        foreach ($bookings as $b) {
            $b->restore();
        }

        //show success message
        session()->flash('success', 'Room restored successfully!');

        //redirect back
        return redirect()->back();

    }

    public function export() 
    {

        return Excel::download(new RoomsExport, 'rooms.xlsx');
    }


    public function showRooms(Request $request)
    {

        // $rooms=Room::paginate(9);


        // if ($request->ajax()) {

        //     return view('roomData')->with('rooms', $rooms);

        // }


        // return view('welcome');


        if (app()->getLocale() == 'nl') {
            setcookie('lang', 'nl');
        }

        else{

            setcookie('lang', 'en');
        }

        return view('welcome');


    }

    public function showDetails($id)
    {

        $room = Room::where('id', $id)->firstOrFail();

        return view('rooms.detail')->with('room', $room);

    }

    public function api()
    {

        return new RoomCollection(Room::with('booking')->get());

    }

    public function roomImportForm()
    {
        
        return view('import');

    }

    public function roomImport(Request $request) 
    {

        Excel::import(new RoomsImport, request()->file('excel'));

        session()->flash('success', 'Room created successfully!');
        
        return redirect('/admin/rooms')->with('rooms', Room::all());

    }

    public function apiShowRooms(Request $request)
    {


        $rooms = Room::all()->toArray();

        return response()->json([
            "success" => true,
            "data" => $rooms], 200);

    }

    public function apiRoomInfo(Request $request, $id)
    {

        $room = Room::where('id', $id)->firstOrFail();
        $user = Auth::user();
        $otherUsers = User::all()->except(Auth::id());

        return response()->json([
            "success" => true,
            "data" => $room,
            "user" => $user,
            "otherUsers" => $otherUsers,
        ], 200);

    }



}

resources/views/rooms/create.blade.php
@extends('layouts.app')

@section('content')


<div class="card card-default">
	
	<div class="card-header">
		{{ isset($room) ? 'Edit Room' : 'Create a Room' }}
	</div>

	<div class="card-body">

		
		<form action="{{ isset($room) ? route('rooms.update', $room->id) : route('rooms.store') }}" method="POST" enctype="multipart/form-data">
			@csrf

			@if(isset($room))
				@method('PUT')
			@endif

			<div class="form-group">
				<label for="name">Name of the room</label>
				
				<input type="text" id="name" class="form-control" name="name" value="{{ isset($room) ? $room->name : old('name') }}" required>

			</div>

			<div class="form-group">
				<label for="descriptionEN">Description in English</label>
				
				<textarea name="descriptionEN" id="descriptionEN" cols="5" rows="5" class="form-control" required>{{ isset($room) ? $room->getTranslation('description', 'en') : old('descriptionEN') }}
				</textarea>

			</div>

			<div class="form-group">
				<label for="descriptionNL">Description in Dutch</label>
				
				<textarea name="descriptionNL" id="descriptionNL" cols="5" rows="5" class="form-control" required>{{ isset($room) ? $room->getTranslation('description', 'nl') : old('descriptionNL') }}
				</textarea>

			</div>

			<div class="form-group">
				<label for="name">Location</label>
				
				<input type="text" id="location" class="form-control" name="location" value="{{ isset($room) ? $room->location : old('Location') }}" required>

			</div>

			@if(isset($room))

				<div class="form-group">
					
					<img id="roomImg" src="{{ asset("storage/app/public/".$room -> image) }}" style="width: 100%" >

				</div>

			@endif

			<div class="form-group">
				<label for="image">Image</label>
				
				<input type="file" id="image" class="form-control" name="image" required>

			</div>


			<div class="form-group">
				
				<button class="btn btn-sm btn-dark" type="submit">{{ isset($room) ? 'Update Room' : 'Create Room'  }}</button>

				<a href="{{url()->previous()}}" class="btn btn-sm btn-outline-dark ml-2">Back</a>


                <a href="{{ route('landingPage', app()->getLocale()) }}" class="btn btn-sm btn-outline-dark ml-2">Home</a>

			</div>

		</form>

	</div>

</div>

@endsection


@section('scripts')

		<script>
		   $(document).ready(function(){
		      $('#image').on("change", function(){
		         $('#roomImg').toggle();
		      });
		   });
		</script>

@endsection

resources/views/rooms/detail.blade.php
@extends('layouts.app')

@extends('layouts.header')

@section('content')

<body>
    <div class="container">
        
        <div class="d-flex justify-content-center">

            <div class="card">
                <div class="row">
                    <aside class="col-sm-5 border-right">
                        <article class="gallery-wrap"> 
                            <div class="img-big-wrap">
                              <div> <a href="#"><img src="{{ asset("storage/".$room -> image) }} " width="110%"></a></div>
                            </div>
                        </article>
                    </aside>

                    <aside class="col-sm-7 pl-5">
                        <article class="card-body p-4">
                            <h2 class="title mb-3">{{$room -> name}}</h2>

                            <dl class="item-property mt-2">
                              <dt>Description</dt>
                              <dd><p>{{$room -> description}}</p></dd>
                            </dl>

                            <div class="row mt-2">
                                <div class="col-sm-5">
                                    <dl class="param param-inline">
                                      <h6><strong> Location: </strong>{{$room->location}}</h6>
                                </div>      
                            </div>

                            <div class="d-flex mt-2">
                                {{-- <form action="" method="get">
                                    @csrf

                                    <input type="hidden" name="room_id" value="{{ $room->id }}">

                                    <button type="submit" class="btn btn-lg btn-primary text-uppercase"> Book </button>

                                </form> --}}

                                <a href="{{ route('bookings.create', $room->id) }}" class="btn btn-lg btn-dark text-uppercase"> BOOK </a>

                                <a href="{{route('landingPage')}}" class="btn btn-lg btn-outline-dark mx-2" style="height: 46px"> HOME </a>
                            </div>
                        </article>
                    </aside>
                </div>
            </div>
        </div>
    </div>
</body>



@endsection 

resources/views/rooms/index.blade.php
@extends('layouts.app')

@section('content')

<div class="d-flex justify-content-end mb-2">

	<a href="{{ route('rooms.create') }}" class="btn btn-dark float-right mx-2">Create Rooms</a>

</div>
<div class="card card-default table-responsive">
	
	<div class="card-header">

		Meeting Rooms

	</div>

	<div class="card-body">
	
		<table class="table">
			
			<thead>
				<th>Image</th>
				<th>Name</th>
				<th>Description</th>
				<th>Location</th>
				<th></th>
				<th></th>
			</thead>

			<tbody>
				@foreach($rooms as $room)
				<tr>
					
					<td><img src="{{ asset("storage/app/public/".$room -> image) }}" width="50" height="50" ></td>
					<td>{{ $room->name }}</td>
					<td>{{ $room->description }}</td>
					<td>{{ $room->location }}</td>
					<td>
						@if (!$room->trashed())
							<a href="{{ route('rooms.edit', $room->id) }}" class="btn btn-info btn-sm"> Edit </a>
						@else

							<form action="{{route('restore-room', $room->id)}}" method="POST">
									@csrf

									@method('PUT')

									<button type="submit" class="btn btn-info btn-sm"> Restore </button>

							</form>
							
						@endif

						

					</td>
					<td> <form action="{{ route('rooms.destroy', $room->id) }}" method="POST">
						
						@csrf

						@method('DELETE')

						<button type="submit" class="btn btn-danger btn-sm">
							{{ $room->trashed() ? 'Delete' : 'Trash' }}
						</button>

					</form>
					</td>

				</tr>
				@endforeach

			</tbody>

		</table>

	</div>

</div>



@endsection